name: LaTeX

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      latex-file: cv-william-wennerstrom.tex
      pdf-file: cv-william-wennerstrom.pdf
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Compile
        uses: xu-cheng/latex-action@1.2.1
        with:
          root_file: ${{ env.latex-file }}
          args: -lualatex --file-line-error --interaction=nonstopmode
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.pdf-file }}
          asset_name: ${{ env.pdf-file }}
          asset_content_type: application/pdf
